### ISSUE TITLE
Feature Request: Enhance Plugin to Include Lyrics

### ISSUE THREAD

**Issue by formeo14** [TrevTV/Lidarr.Plugin.Deezer#2]
**Description:**
The current plugin outperforms the one from ta264 that integrates with deemix. However, it lacks the functionality to download lyrics from Deezer. Deezer's lyrics, although mostly unsynchronized, offer a broader selection compared to Spotify. Deemix already supports downloading and embedding these lyrics into the song files, which can then be read without issues by media servers like Jellyfin.
I propose adding an option to the plugin to download lyrics from Deezer and embed them into the song files.

**Additional Feature:**
An additional feature could be to integrate with an lrclib instance like lrclib.net to fetch synchronized lyrics. This could potentially be implemented similarly to how lidarr can be configured to copy other files like .lrc files during import. However, it is unclear if this is feasible due to potential issues with file remaining during import.

**Context:**
Including both raw and synchronized lyrics would make this plugin a great solution for users looking to enhance their music library DeezNet.

If you find yourself with some spare time and are inclined to work on this feature, it would be fantastic. 
Do so at your own pace; I don't want to impose any pressure on you.

**Comment by TrevTV** [comment]
Appreciate the contribution to DeezNET, made this a lot easier! Implemented it in 678c1417e1a8a7c09b567396126559d35914f75d and e94762d8cbed049592f42d63bbe817146cb59486, will try to make a release within the next couple days.

**Comment by formeo14** [comment]
Works great. Thank you!
